server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: cs-flow

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: cs-flow